-- ==========================================================
-- SKEMA DATABASE SUPABASE: WASAP DAILY HUB (ALL-IN-ONE)
-- Jalankan query ini di Menu "SQL Editor" pada Supabase Dashboard
-- ==========================================================

-- 1. Tabel Users (Autentikasi Multi-Tenant)
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  phone_number TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  password_raw TEXT,
  role TEXT DEFAULT 'user', -- 'admin' | 'user'
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Migrasi kolom password_raw jika belum ada
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS password_raw TEXT;

-- 2. Tabel Tasks (Tugas Harian, Reminder Jam Bebas & Kalender Dinding)
CREATE TABLE IF NOT EXISTS public.tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone_number TEXT,
  title TEXT NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'done', 'draft')),
  task_date DATE DEFAULT CURRENT_DATE,
  due_time TIME,
  is_reminder BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabel Expenses (Pengeluaran Keuangan)
CREATE TABLE IF NOT EXISTS public.expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone_number TEXT,
  amount BIGINT NOT NULL,
  category TEXT DEFAULT 'Lainnya',
  description TEXT NOT NULL,
  expense_date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabel Incomes (Pemasukan Keuangan)
CREATE TABLE IF NOT EXISTS public.incomes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone_number TEXT,
  amount BIGINT NOT NULL,
  category TEXT DEFAULT 'Gaji',
  description TEXT NOT NULL,
  income_date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabel Threads (Yap Planner & Content Calendar)
CREATE TABLE IF NOT EXISTS public.threads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone_number TEXT,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  yap_category TEXT DEFAULT 'Relatable',
  platform TEXT DEFAULT 'Threads',
  scheduled_date DATE DEFAULT CURRENT_DATE,
  scheduled_time TIME DEFAULT '19:00:00',
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'scheduled', 'posted', 'archived')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Tabel Admin Notes (Catatan Internal Khusus Admin)
CREATE TABLE IF NOT EXISTS public.admin_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Migrasi Kolom Tambahan (Idempotent)
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS phone_number TEXT;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS due_time TIME;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS is_reminder BOOLEAN DEFAULT false;

ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS phone_number TEXT;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'Lainnya';

ALTER TABLE public.incomes ADD COLUMN IF NOT EXISTS phone_number TEXT;
ALTER TABLE public.incomes ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'Gaji';

-- 8. Index Pencarian Cepat
CREATE INDEX IF NOT EXISTS idx_tasks_phone ON public.tasks(phone_number);
CREATE INDEX IF NOT EXISTS idx_tasks_date ON public.tasks(task_date);
CREATE INDEX IF NOT EXISTS idx_expenses_phone ON public.expenses(phone_number);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON public.expenses(expense_date);
CREATE INDEX IF NOT EXISTS idx_incomes_phone ON public.incomes(phone_number);
CREATE INDEX IF NOT EXISTS idx_incomes_date ON public.incomes(income_date);
CREATE INDEX IF NOT EXISTS idx_threads_phone ON public.threads(phone_number);
CREATE INDEX IF NOT EXISTS idx_threads_date ON public.threads(scheduled_date);
CREATE INDEX IF NOT EXISTS idx_users_phone ON public.users(phone_number);
CREATE INDEX IF NOT EXISTS idx_users_username ON public.users(username);

-- 9. Row Level Security (RLS Policies)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all on users" ON public.users;
CREATE POLICY "Allow all on users" ON public.users FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all on tasks" ON public.tasks;
CREATE POLICY "Allow all on tasks" ON public.tasks FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all on expenses" ON public.expenses;
CREATE POLICY "Allow all on expenses" ON public.expenses FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.incomes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all on incomes" ON public.incomes;
CREATE POLICY "Allow all on incomes" ON public.incomes FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.threads ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all on threads" ON public.threads;
CREATE POLICY "Allow all on threads" ON public.threads FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.admin_notes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all on admin_notes" ON public.admin_notes;
CREATE POLICY "Allow all on admin_notes" ON public.admin_notes FOR ALL USING (true) WITH CHECK (true);
