-- ==========================================================
-- SKEMA DATABASE SUPABASE: WASAP DAILY HUB (MULTI-USER)
-- Jalankan query ini di Menu "SQL Editor" pada Supabase Dashboard
-- ==========================================================

-- 1. Buat Tabel Users
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  phone_number TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT DEFAULT 'user', -- 'admin' | 'user'
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Buat Tabel Tasks (Mendukung Reminder Jam Bebas & Kalender)
CREATE TABLE IF NOT EXISTS public.tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone_number TEXT,
  title TEXT NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'done', 'draft')),
  task_date DATE DEFAULT CURRENT_DATE,
  due_time TIME,
  is_reminder BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Buat Tabel Expenses
CREATE TABLE IF NOT EXISTS public.expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone_number TEXT,
  amount BIGINT NOT NULL,
  description TEXT NOT NULL,
  expense_date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Pastikan Kolom-Kolom Baru Tersedia (Idempotent Migration)
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS phone_number TEXT;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS due_time TIME;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS is_reminder BOOLEAN DEFAULT false;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS phone_number TEXT;

-- 5. Buat Index Pencarian Cepat
CREATE INDEX IF NOT EXISTS idx_tasks_phone ON public.tasks(phone_number);
CREATE INDEX IF NOT EXISTS idx_tasks_date ON public.tasks(task_date);
CREATE INDEX IF NOT EXISTS idx_expenses_phone ON public.expenses(phone_number);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON public.expenses(expense_date);
CREATE INDEX IF NOT EXISTS idx_users_phone ON public.users(phone_number);
CREATE INDEX IF NOT EXISTS idx_users_username ON public.users(username);
